### ISSUE TITLE
Closed and re-opened in-between tabs don't move tabs and marker

### ISSUE THREAD

**Issue by your-acc** [NWinXP/Aerofox#1]
Accidentally found a bug during use, which also applies to 07Fox.
https://user-images.githubusercontent.com/82058673/219526124-2d49c411-61ab-4e49-b815-b755269f1885.mp4
https://user-images.githubusercontent.com/82058673/219526130-b21b790c-c72a-4fc1-a694-ec23590091cc.mp4

**Comment by NWinXP** [comment]
You need to set ui.prefersReducedMotion to 1, as stated in the install instructions.
Closing issue.
