### ISSUE TITLE
Any way to pack the needed parameters into the files themselves?

### ISSUE THREAD

**Issue by zaafonin** [NWinXP/Aerofox#2]
It would be very appreciated if the necessary layout was pre-set so one could achieve it just by copying the files. On firefox 110 stuff is already very wonky (can't set spacers, elements disappear when dragging). On that note, will there be a release for the latest Firefox ESR (102.8)? ESR releases happen less often, so it's kind of LTS and they won't break much stuff there.

**Comment by NWinXP** [comment]
The layout can be pre-set by copying user.js, but I have not implemented that.
Firefox 110 is not supported and I do not plan to update the theme for it.
I also do not plan to make the theme available for ESR 102.
Closing issue.
